package com.park.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ParkServletService service = new ParkServletService();
 * ParkServletDelegate portType = service.getParkServletPort();
 * portType.areaParkInfo(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ParkServletService", targetNamespace = "http://action.jiuyu.com/", wsdlLocation = "http://220.248.75.39:880/UserMgrService/ParkServletPort?wsdl")
public class ParkServletService extends Service {

	private final static URL PARKSERVLETSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.park.service.ParkServletService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.park.service.ParkServletService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://220.248.75.46:29918/UserMgrService/ParkServletPort?wsdl");
		} catch (MalformedURLException e) {
//			logger
//					.warning("Failed to create URL for the wsdl Location: 'http://220.248.75.46:29918/UserMgrService/ParkServletPort?wsdl', retrying as a local file");
//			logger.warning(e.getMessage());
		}
		PARKSERVLETSERVICE_WSDL_LOCATION = url;
	}

	public ParkServletService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ParkServletService() {
		super(PARKSERVLETSERVICE_WSDL_LOCATION, new QName(
				"http://action.jiuyu.com/", "ParkServletService"));
	}

	/**
	 * 
	 * @return returns ParkServletDelegate
	 */
	@WebEndpoint(name = "ParkServletPort")
	public ParkServletDelegate getParkServletPort() {
		return super.getPort(new QName("http://action.jiuyu.com/",
				"ParkServletPort"), ParkServletDelegate.class);
	}

}
