package com.park.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ParkServletDelegate", targetNamespace = "http://action.jiuyu.com/")
public interface ParkServletDelegate {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "areaParkInfo", targetNamespace = "http://action.jiuyu.com/", className = "com.jiuyu.action.AreaParkInfo")
	@ResponseWrapper(localName = "areaParkInfoResponse", targetNamespace = "http://action.jiuyu.com/", className = "com.jiuyu.action.AreaParkInfoResponse")
	public String areaParkInfo(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "singleParkInfo", targetNamespace = "http://action.jiuyu.com/", className = "com.jiuyu.action.SingleParkInfo")
	@ResponseWrapper(localName = "singleParkInfoResponse", targetNamespace = "http://action.jiuyu.com/", className = "com.jiuyu.action.SingleParkInfoResponse")
	public String singleParkInfo(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "areainfo", targetNamespace = "http://action.jiuyu.com/", className = "com.jiuyu.action.Areainfo")
	@ResponseWrapper(localName = "areainfoResponse", targetNamespace = "http://action.jiuyu.com/", className = "com.jiuyu.action.AreainfoResponse")
	public String areainfo(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "singleinfo", targetNamespace = "http://action.jiuyu.com/", className = "com.jiuyu.action.Singleinfo")
	@ResponseWrapper(localName = "singleinfoResponse", targetNamespace = "http://action.jiuyu.com/", className = "com.jiuyu.action.SingleinfoResponse")
	public String singleinfo(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Issendarea")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "Issendarea", targetNamespace = "http://action.jiuyu.com/", className = "com.jiuyu.action.Issendarea")
	@ResponseWrapper(localName = "IssendareaResponse", targetNamespace = "http://action.jiuyu.com/", className = "com.jiuyu.action.IssendareaResponse")
	public String issendarea(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Issendsingle")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "Issendsingle", targetNamespace = "http://action.jiuyu.com/", className = "com.jiuyu.action.Issendsingle")
	@ResponseWrapper(localName = "IssendsingleResponse", targetNamespace = "http://action.jiuyu.com/", className = "com.jiuyu.action.IssendsingleResponse")
	public String issendsingle(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getio", targetNamespace = "http://action.jiuyu.com/", className = "com.jiuyu.action.Getio")
	@ResponseWrapper(localName = "getioResponse", targetNamespace = "http://action.jiuyu.com/", className = "com.jiuyu.action.GetioResponse")
	public String getio(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2);

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getareaio", targetNamespace = "http://action.jiuyu.com/", className = "com.jiuyu.action.Getareaio")
	@ResponseWrapper(localName = "getareaioResponse", targetNamespace = "http://action.jiuyu.com/", className = "com.jiuyu.action.GetareaioResponse")
	public String getareaio(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3);

	/**
	 * 
	 * @param arg4
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getoneio", targetNamespace = "http://action.jiuyu.com/", className = "com.jiuyu.action.Getoneio")
	@ResponseWrapper(localName = "getoneioResponse", targetNamespace = "http://action.jiuyu.com/", className = "com.jiuyu.action.GetoneioResponse")
	public String getoneio(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3,
			@WebParam(name = "arg4", targetNamespace = "") String arg4);

}
